error screen while changing theme
CCExtractor/ultimate_alarm_clock pull request #123
Opened 2023-10-25 18:01 UTC by RunTerror

### Description
wrong controller was passed to widgets, created a settingscontroller instance and passed it to widgets.

## Fixes #119 

## Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/113206442/88532af6-5720-4cfb-8448-5ecacfea1d54

2023-10-26 04:09 UTC, superiorsd10 commented
Hey @RunTerror 👋
It isn't about the wrong controller as the `SettingsView` extends GetView<SettingsController>, so the controller there is SettingsController that you're trying to find.

2023-10-26 11:13 UTC, RunTerror commented
@superiorsd10  ya i know that controller was also settingsviewcontroller but passing that controller was giving that error screen and by passing new instance of same solves the issue 🙂

2023-11-06 11:57 UTC, MarkisDev commented
@RunTerror Hey, have you tried checking with the fenix property for controllers in the binding? Maybe while you're at it, change it to put from lazyPut for the SettingsController. 

I think the controller is just being destroyed when you navigate back.

2023-11-12 04:10 UTC, RunTerror commented
@MarkisDev  now i used put over lazyput i didn't encountered any issue now. Ig you are right the controller gets destroyed when we pop the screen.

2023-11-13 16:38 UTC, MarkisDev requested changes

2023-11-13 16:38 UTC, MarkisDev commented on lib/app/modules/settings/views/settings_view.dart
> +  SettingsController settingsController=Get.put(SettingsController());
I think you should update the bindings rather than the view file to fetch settingsController.

2023-11-14 04:14 UTC, RunTerror commented
i already tried and debug, the controller gets destroyed again when i create a new instance of it on view screen the problem solves. Can u please tell me why this thing is happening.

2023-11-14 08:06 UTC, MarkisDev commented
Alright. So let me quickly explain put vs lazyPut.

`Get.put()` will essentially inject the dependency (in this case it is our SettingsController which holds the business logic) immediately and will begin executing it (even if the controller isn't required)

`Get.lazyPut` is _slightly better_ because it will only inject the dependency (SettingsController) when it is needed, saving some memory.

This issue arises because when you're navigating back to HomePage the controller isn't being destroyed and hence not being recreated when you go back to SettingsPage once again. The reason it isn't being recreated is because HomePage also depends on SettingsController. That's the reason `find` was working because you were accessing the instance of settingsController created in HomePage.

The fix for this lies with the `fenix` property that can be attached to the `lazyPut` which allows the controller to be reconstructed (after being disposed). You need to add `fenix: true` to the `home_binding.dart` as well as `settings_binding.dart` only for the SettingsController which will allow it to be reconstructed when needed and disposed when not needed.

Hope that helps, please feel free to ask any questions when you're stuck!

2023-11-17 05:37 UTC, RunTerror commented
@MarkisDev  this helped alot in understand why error screen was showing up please review my changes . Thank you this means alot.

2023-11-26 17:06 UTC, merged