Feature Addition: About Section in Settings
CCExtractor/ultimate_alarm_clock pull request #145
Opened 2023-11-13 19:01 UTC by andoriyaprashant

### Description
The About section serves as a centralized hub for essential information, combining aesthetics with functionality. Users can now quickly access the app's logo, GitHub repository, official website, and version details. This addition aligns with best practices for transparency and user engagement.

### Proposed Changes
***Settings Section:***

- Added a dedicated "About" section in the app's Settings menu.
- Users can now access important information and links related to the application.

***About View:***

- Included the application logo for a visually appealing presentation.
- Provided a GitHub link, allowing users to explore and contribute to the project on GitHub.
- Added a link to the official website, providing users with additional resources and information.

***Version Information:***

Displayed the current version of the application, making it easier for users to track updates.

## Fixes #69 

## Demo Video

https://github.com/CCExtractor/ultimate_alarm_clock/assets/121665385/747da690-9465-41a5-b684-3a20e2e1d14c

## Screenshots

<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/121665385/24036cce-a5e1-4199-a444-51d9bc2a9cef" width="300" alt="Screenshot 1">

<img src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/121665385/992cca90-7f33-42ac-9670-e5449d2c471f" width="300" alt="Screenshot 2">

## Checklist

- [X] Tests have been added or updated to cover the changes
- [X] Documentation has been updated to reflect the changes
- [X] Code follows the established coding style guidelines
- [X] All tests are passing

2023-11-14 07:18 UTC, MarkisDev commented on lib/app/modules/settings/views/about_view.dart
> +                      String url = "https://ccextractor.org/";
Please move the url to the controller

2023-11-14 07:18 UTC, MarkisDev commented on lib/app/modules/settings/views/about_view.dart
> +  Future<bool> launchUrl(Uri uri) async {
move this function to the controller as well

2023-11-14 07:19 UTC, MarkisDev commented on lib/app/modules/settings/views/about_view.dart
> +                      String url =
move this to the controller as well

2023-11-14 07:19 UTC, MarkisDev commented on lib/app/modules/settings/views/about_view.dart
This file should come under the about/views to follow the project's structure.

2023-11-14 07:20 UTC, MarkisDev commented on lib/app/modules/settings/bindings/about_binding.dart
This file should come under about/bindings as well to follow the project structure.

2023-11-14 07:21 UTC, MarkisDev commented on lib/app/modules/settings/views/settings_view.dart
> +                 AboutSection(
Instead of doing this, just make about as a different page using get_cli and navigate to it via GetX.

2023-11-14 07:23 UTC, MarkisDev requested changes
The code seems alright but the project structure hasn't been followed. Please use get_cli to create a new about page and link to it (the views, controllers and bindings should be in the about directory which get_cli will handle for you).

If you have any questions, feel free to ask them. Happy to help!

2023-11-14 07:26 UTC, andoriyaprashant commented
> The code seems alright but the project structure hasn't been followed. Please use get_cli to create a new about page and link to it (the views, controllers and bindings should be in the about directory which get_cli will handle for you).
> 
> If you have any questions, feel free to ask them. Happy to help!

Okay @MarkisDev I will implement these required changes as soon as possible 
Thank you for your guidance

2023-11-14 14:53 UTC, andoriyaprashant commented
Hello @MarkisDev as you instructed, I have changed the location of the files 
![Screenshot 2023-11-14 194307](https://github.com/CCExtractor/ultimate_alarm_clock/assets/121665385/8cb2f093-7143-47ae-96e4-47b40426236e)

2023-11-17 13:12 UTC, superiorsd10 commented
Hello @andoriyaprashant 👋
Nice work man! But I would like to make some suggestions here, 

- In the `app_routes.dart` inside the `routes` folder, you've declared a Path i.e. `static const ABOUT = '/about-view';` but according to the convention followed, you shouldn't suffix the route with `view`. So it should be `static const ABOUT = '/about';` only. 
- You've created a new file named `about.dart` inside the `About` module. But that file should be present in the `views` folder of the `Settings` module. All other tiles are also present there.  

Thank you,

2023-11-22 20:59 UTC, andoriyaprashant commented
> Hello @andoriyaprashant 👋 Nice work man! But I would like to make some suggestions here,
> 
> * In the `app_routes.dart` inside the `routes` folder, you've declared a Path i.e. `static const ABOUT = '/about-view';` but according to the convention followed, you shouldn't suffix the route with `view`. So it should be `static const ABOUT = '/about';` only.
> * You've created a new file named `about.dart` inside the `about` module. But that file should be present in the `views` folder of the `settings` module. All other tiles are also present there.
> * The module title should be in lowercase i.e. 'about' instead of 'About'.
> * Instead of making `AboutView` a stateless widget, you can use `GetView`.
> 
> Thank you,

Thank you for the suggestion @superiorsd10👍🏻 I have made the necessary changes. You can check them now

2023-11-26 16:59 UTC, MarkisDev approved these changes

2023-11-26 17:01 UTC, merged