Add quick note
CCExtractor/ultimate_alarm_clock pull request #235
Opened 2023-12-15 11:43 UTC by its-me-abhishek

### Description
Added quick note facility
### Proposed Changes

## Fixes #200 

## Screenshots
![1](https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/e0007fbd-af5e-4320-8ac7-7ecdf1c2e6b8)
![5](https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/5d304b44-3bee-4696-8fb5-edf6ac981a62)
![4](https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/776a7fd0-435d-4ecd-a236-df6ac3cd8dc3)
![2](https://github.com/CCExtractor/ultimate_alarm_clock/assets/114338679/a56eb8df-81a0-4dc8-99cb-cdbf59ca4678)

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

2023-12-15 14:57 UTC, its-me-abhishek commented
Please review my PR @MarkisDev

2023-12-16 10:32 UTC, MarkisDev requested changes
The about page has to be checked again and any reason why you've changed the ringtone functionality?

2023-12-16 10:32 UTC, MarkisDev commented on lib/app/modules/about/views/about_view.dart
> -                "This project was originally developed as part of Google Summer of code under the CCExtractor organization. It's free, the source code is available, and we encourage programmers to co
Please revert this change. We have changed the version and text.

2023-12-16 10:32 UTC, MarkisDev commented on lib/app/utils/utils.dart
> -  static Future<void> playCustomSound(String customRingtonePath) async {
Why have you removed the function?

2023-12-16 10:34 UTC, MarkisDev commented on lib/app/modules/alarmRing/views/alarm_ring_view.dart
> +                          'Quick Note',
Also we should probably just call it note

2023-12-16 10:35 UTC, MarkisDev commented on lib/app/modules/alarmRing/views/alarm_ring_view.dart
> +                              .displayLarge!
Maybe use a different font for the note as well

2023-12-16 10:51 UTC, its-me-abhishek commented
These might have happened as after syncing with the latest commits that changed the version of the application/redo-ed the custom ringtone, my main branch PR had got a lot of conflict issues. I'll make a new branch and then redo the quick note facility as I did not intend to change or alter the About page or the Ringtone functions.

2023-12-16 11:00 UTC, MarkisDev commented
> These might have happened as after syncing with the latest commits that changed the version of the application/redo-ed the custom ringtone, my main branch PR had got a lot of conflict issues. I'll make a new branch and then redo the quick note facility as I did not intend to change or alter the About page or the Ringtone functions.

That's okay, it happens! Remember to never put up a PR which has merge conflicts :)

2023-12-16 11:05 UTC, its-me-abhishek commented
Got it! Also, shall I close this PR and put up a newer one?

2023-12-16 11:06 UTC, MarkisDev commented
Sure, that should be fine.

On Sat, Dec 16, 2023, 16:35 Abhishek ***@***.***> wrote:

> Got it! Also, shall I close this PR and put up a newer one?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CCExtractor/ultimate_alarm_clock/pull/235#issuecomment-1858790805>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG3GLJ6OEWAFTFOUPNFHFQTYJV573AVCNFSM6AAAAABAWKIZPGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJYG44TAOBQGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-16 11:06 UTC, closed without merging