rkverma2022/Extending swipe-to-delete with confirmation to delete feature
CCExtractor/ultimate_alarm_clock pull request #324
Opened 2024-01-10 12:55 UTC by rkverma2022

### Description

### Proposed Changes

## Fixes #(321)

## Screenshots

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

2024-01-13 16:38 UTC, MarkisDev requested changes

2024-01-13 16:38 UTC, MarkisDev commented on lib/app/modules/home/views/home_view.dart
> +  return await showDialog(
You'll have to use GetX for dialog since that is what we've been using so far for all our dialogs.

2024-01-13 16:38 UTC, MarkisDev commented on lib/app/modules/home/views/home_view.dart
> +              TextButton(
Also, please make sure the buttons are consistent with the theme - A good example can be found in the confirmation to navigate away from the addOrUpdate screen

2024-01-14 08:39 UTC, rkverma2022 commented
@MarkisDev 

update:

https://github.com/CCExtractor/ultimate_alarm_clock/assets/112231455/706d94b0-47c1-4835-99b5-dc600b465825

I am looking forward to your feedback, and if any other changes are needed, please let me know.

Thank You

2024-01-21 16:39 UTC, MarkisDev requested changes

2024-01-21 16:39 UTC, MarkisDev commented on lib/app/modules/home/views/home_view.dart
> +    var result = await Get.dialog<bool>(
This is not what I meant. You'd have to use a dialog consistent with the one you see when you try to navigate back to home from addOrUpdate screen. You can use a `defaultDialog` but follow the same theme (background color, button placements, button style etc.)

2024-03-02 17:01 UTC, MarkisDev commented
Closing this PR since it's stale now. Please feel free to reopen.

2024-03-02 17:01 UTC, closed without merging