Undo added on swipe to delete alarm using ScaffoldMessenger
CCExtractor/ultimate_alarm_clock pull request #326
Opened 2024-01-11 10:58 UTC by Deepanshuigtm

### Description
This Flutter project implements a swipe-to-delete feature for managing alarms, enhancing the user experience with an "Undo" option using ScaffoldMessenger. When users swipe to delete an alarm, the application temporarily stores the deleted alarm model in a variable, displaying a Snackbar with an "Undo" option. The Snackbar is powered by ScaffoldMessenger.of(context).showSnackBar and has a duration of 4 seconds, allowing users to easily undo the deletion within that timeframe

### Proposed Changes

1. Used ScaffoldMessenger.of(context).showSnackBar to create a Snackbar for displaying the "Undo" feature.
2. Design the Snackbar to include an "Undo" button, providing users with an option to reverse the deletion.
3. When the user taps "Undo" within the Snackbar, restore the previously deleted alarm model back to the database.
4. Set the duration of the Snackbar to 4 seconds, providing users with a reasonable timeframe to decide whether to undo the deletion.
5. Optimize the visual representation of the alarms to make the swipe-to-delete and undo features intuitive.

## Fixes #314 

## Screenshots

https://github.com/CCExtractor/ultimate_alarm_clock/assets/91874023/a6e55dbd-ce3b-4fb0-999e-3b7f4b5f3c9b

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

2024-01-13 16:45 UTC, MarkisDev requested changes

2024-01-13 16:45 UTC, MarkisDev commented on lib/app/modules/home/views/home_view.dart
> +                                          AlarmModel? alarm_to_delete;
Let's move this to the controller and access it here via the controller.

2024-01-13 16:45 UTC, MarkisDev commented on lib/app/modules/home/views/home_view.dart
> +                                          ScaffoldMessenger.of(context).showSnackBar(
Maybe we could use GetX snackbar? Would keep everything consistent.

2024-01-13 18:06 UTC, Deepanshuigtm reviewed
created a method in controller and also changed to Get snacker please review

2024-01-15 11:58 UTC, MarkisDev approved these changes

2024-01-15 11:58 UTC, merged