this commit is regarding the issue #284
CCExtractor/ultimate_alarm_clock pull request #346
Opened 2024-01-15 16:41 UTC by nikkivirtuoso

### Description

I have done some minor changes and along with this i have resolved nits that make the code seems clear and easy to understand

### Proposed Changes

## Fixes #(284)

Replace `284` with the issue number which is fixed in this PR

## Screenshots

<img width="351" alt="Screenshot 2024-01-15 at 10 10 41 PM" src="https://github.com/CCExtractor/ultimate_alarm_clock/assets/148634283/5d3bfcac-95d6-450e-bf0f-776923cb580f">

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

2024-01-15 16:44 UTC, nikkivirtuoso commented
@MarkisDev sir please have a look

2024-01-16 11:36 UTC, cfsmp3 commented
Please edit the subject so it says what it actually does :-)

2024-01-17 06:09 UTC, nikkivirtuoso commented
@cfsmp3 sir, please have a look i have updated the subject

2024-01-21 16:52 UTC, MarkisDev requested changes

2024-01-21 16:52 UTC, MarkisDev commented on lib/app/modules/settings/views/language_menu.dart
> +                    setState(() {
We're using GetX for state management so you'll have to fix that.

2024-01-21 16:58 UTC, MarkisDev commented
Also, I couldn't find the fix for #284 in this PR. Am I missing something? Please let me know :)

2024-03-02 16:29 UTC, MarkisDev commented
Closing since its stale, please feel free to make a new one if there's anything else.

2024-03-02 16:29 UTC, closed without merging