Remove the previous "Undo" option before displaying the new one
CCExtractor/ultimate_alarm_clock pull request #354
Opened 2024-01-16 18:29 UTC by Deepanshuigtm

### Description
When swiping to delete multiple alarms simultaneously, the application does not remove the previous "Undo" option before displaying the new one. This behavior can lead to confusion as users may unintentionally trigger the wrong undo action.

### Proposed Changes
Added a check to clear the current Snackbar if it is open before displaying a new one

## Fixes #353 

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

2024-01-17 18:44 UTC, MarkisDev requested changes

2024-01-17 18:44 UTC, MarkisDev commented on lib/app/modules/home/controllers/home_controller.dart
> +    Get.back();
Might be a better idea to use GetX to check if snackbars are active using `isSnackbarOpen` and close it using `closeAllSnackBars`

2024-01-17 19:20 UTC, Deepanshuigtm reviewed
used a check method issnackbar open then close all snackbar please review

2024-01-21 15:59 UTC, merged

2024-01-25 05:54 UTC, superiorsd10 commented
Hello @Deepanshuigtm 👋

I hope you're doing well. I was working on issue #370 and I just wanna ask if there is any particular reason for changing the snack bar UI.

Thank you,

2024-01-28 03:54 UTC, Deepanshuigtm commented
Hello  @superiorsd10 

I initially used Get.snackbar for the snackbar, but later, I modified it. I believe it utilized default themes, which might be the reason for the change in the snackbar UI.