Feature: Audio Preview
CCExtractor/ultimate_alarm_clock pull request #365
Opened 2024-01-19 19:48 UTC by duckcommit

### Description
User can now preview the audio before selecting the tone, hence reducing confusion between multiple audios, especially if we add more options from our side.

## Fixes #364 

## Screenshots
https://github.com/CCExtractor/ultimate_alarm_clock/assets/22213675/76752164-39c4-4fe5-a9c6-58bbd896c5ca

## Checklist

- [x] Multiple Tests/Checks
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines

2024-01-21 17:25 UTC, MarkisDev requested changes

2024-01-21 17:25 UTC, MarkisDev commented on lib/app/utils/audio_utils.dart
> +  static bool isPreviewing = false;
Please move this to the begining of the file, all variables are kept there.

2024-01-21 19:06 UTC, duckcommit reviewed
Yes, I have made that change @MarkisDev

2024-01-24 13:50 UTC, MarkisDev commented
@duckcommit  You'll have to resolve the conflicts and recheck the code since it's changed.

2024-01-25 09:56 UTC, duckcommit reviewed
The conflicts are now solved. I have tried the code too, it runs fine @MarkisDev .

2024-01-25 10:09 UTC, MarkisDev approved these changes

2024-01-25 10:09 UTC, merged