Enhanced Timer by adding new feature
CCExtractor/ultimate_alarm_clock pull request #487
Opened 2024-03-03 14:56 UTC by nidhin29

Description

The timer is enhanced by adding pomodoro feature

Proposed Changes

https://github.com/CCExtractor/ultimate_alarm_clock/assets/131900819/7c81fff6-a38a-4751-b116-56b5de5ad8e8

Fixes https://github.com/CCExtractor/ultimate_alarm_clock/issues/156

2024-03-03 15:01 UTC, nidhin29 commented
@MarkisDev Sir, I had some misunderstandings I have added the pomodoro feature as expected

2024-03-03 15:01 UTC, nidhin29 commented
@MarkisDev Sir, is this fine

2024-03-10 14:11 UTC, MarkisDev commented
This definitely does work, but I think we need a switch or something to allow the user to switch to a pomodoro timer. We aren't looking to replace the timer, just add onto it.

2024-03-10 14:14 UTC, MarkisDev requested changes

2024-03-10 14:14 UTC, MarkisDev commented on lib/app/modules/timer/views/timer_view.dart
We can probably add a switch which when enabled can turn the normal timer into a pomodoro style. Otherwise, it'll function as a normal timer.

2024-03-10 14:30 UTC, nidhin29 commented on lib/app/modules/timer/views/timer_view.dart
Sir,What i have done is that if the break time is 0 then it will work as normal timer

2024-03-10 14:36 UTC, nidhin29 commented
@MarkisDev Sir, I understand what you said but what i have done is that if the break time is zero then it will function as a normal timer otherwise pomodoro

2024-03-10 14:50 UTC, MarkisDev commented
> @MarkisDev Sir, I understand what you said but what i have done is that if the break time is zero then it will function as a normal timer otherwise pomodoro

That would just make things more confusing for a person who wants to use the normal timer. We should just hide the break section for a pomodoro timer unless its necessary.

2024-03-16 14:04 UTC, closed without merging